In [1]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification
import torch

In [2]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [4]:
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-cased", num_labels=249)

Some weights of the model checkpoint at distilbert-base-cased were not used when initializing DistilBertForSequenceClassification: ['vocab_layer_norm.weight', 'vocab_projector.bias', 'vocab_layer_norm.bias', 'vocab_transform.bias', 'vocab_projector.weight', 'vocab_transform.weight']
- This IS expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['pre_classifier.weight', 'classifier.bias', 'classifier.wei

In [27]:
tok = tokenizer('very short sentence')
tok['input_ids'] = torch.IntTensor(tok['input_ids']).unsqueeze(0)
tok['attention_mask'] = torch.FloatTensor(tok['attention_mask']).unsqueeze(0)
tok['labels'] = torch.LongTensor([1]).unsqueeze(0)
tok

{'input_ids': tensor([[ 101, 2200, 2460, 6251,  102]], dtype=torch.int32), 'attention_mask': tensor([[1., 1., 1., 1., 1.]]), 'labels': tensor([[1]])}

In [42]:
model.train()
output = model(**tok)

In [29]:
output

SequenceClassifierOutput(loss=tensor(5.7902, grad_fn=<NllLossBackward0>), logits=tensor([[-0.0733, -0.2730,  0.0874, -0.2341, -0.0825, -0.1254,  0.1460,  0.1089,
         -0.0238,  0.0260,  0.0132, -0.0582,  0.0576, -0.0418,  0.0463, -0.2343,
          0.0236,  0.2402,  0.1530, -0.0240,  0.0248, -0.0498, -0.0090, -0.0730,
          0.0769,  0.0126,  0.1880, -0.0205, -0.1003, -0.1764, -0.2090, -0.0735,
          0.0355,  0.0968, -0.2817,  0.0178,  0.3019,  0.0374,  0.0959,  0.0960,
         -0.0586, -0.0078, -0.1070, -0.0422,  0.0511,  0.0527,  0.2269, -0.0964,
         -0.1354, -0.1101, -0.1880,  0.2243,  0.0137,  0.0283,  0.1067, -0.0058,
          0.1281, -0.0755,  0.0505,  0.1603, -0.0657, -0.0759,  0.1440, -0.0405,
          0.0937, -0.1067, -0.1039,  0.0220, -0.1928, -0.2575, -0.1249,  0.0913,
          0.0358, -0.1403, -0.0971,  0.0897,  0.0254,  0.0053, -0.0612, -0.1127,
         -0.0189,  0.0776, -0.0184, -0.1279, -0.0047, -0.0018, -0.1181, -0.1085,
          0.0393,  0.1631, -

In [34]:
output.logits

tensor([[-0.0733, -0.2730,  0.0874, -0.2341, -0.0825, -0.1254,  0.1460,  0.1089,
         -0.0238,  0.0260,  0.0132, -0.0582,  0.0576, -0.0418,  0.0463, -0.2343,
          0.0236,  0.2402,  0.1530, -0.0240,  0.0248, -0.0498, -0.0090, -0.0730,
          0.0769,  0.0126,  0.1880, -0.0205, -0.1003, -0.1764, -0.2090, -0.0735,
          0.0355,  0.0968, -0.2817,  0.0178,  0.3019,  0.0374,  0.0959,  0.0960,
         -0.0586, -0.0078, -0.1070, -0.0422,  0.0511,  0.0527,  0.2269, -0.0964,
         -0.1354, -0.1101, -0.1880,  0.2243,  0.0137,  0.0283,  0.1067, -0.0058,
          0.1281, -0.0755,  0.0505,  0.1603, -0.0657, -0.0759,  0.1440, -0.0405,
          0.0937, -0.1067, -0.1039,  0.0220, -0.1928, -0.2575, -0.1249,  0.0913,
          0.0358, -0.1403, -0.0971,  0.0897,  0.0254,  0.0053, -0.0612, -0.1127,
         -0.0189,  0.0776, -0.0184, -0.1279, -0.0047, -0.0018, -0.1181, -0.1085,
          0.0393,  0.1631, -0.1474, -0.1183,  0.0563,  0.1378,  0.0582,  0.0854,
          0.0393, -0.0108, -

In [37]:
torch.argmax(output.logits, dim=-1)

tensor([205])

In [39]:
torch.softmax(output.logits, dim=1)

tensor(1.0000, grad_fn=<SumBackward0>)

In [45]:
output.logits.type(torch.int).argmax(dim=-1)

tensor([0])

In [51]:
output.logits.type(torch.int).argmax(dim=-1).unsqueeze(0).shape

torch.Size([1, 1])

In [3]:
target = torch.tensor([0, 1, 2])
preds = torch.tensor([[0.1, 0.9, 0], [0.3, 0.1, 0.6], [0.2, 0.5, 0.3]])
target.shape, preds.shape

(torch.Size([3]), torch.Size([3, 3]))

In [12]:
preds.unsqueeze(-1).squeeze(-1).shape

torch.Size([3, 3])